### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by Kristinita** [lindskogen/InstacodeSublime#1]
Please, update Instacode, that plugin to work correctly in 2016. Now name of service — [instaco.de](http://instaco.de/). Thanks.

**Comment by lindskogen** [comment]
It would seem that the new version of Instacode doesn't support publishing via the same method as I used before. After a bit of looking around, no other editor plugin is updated either...

Waiting for now. Until I can find a method to publish the code again.

**Comment by Kristinita** [comment]
I wrote a letter to the author Instaco.de, he corrected errors. Now InstacodeSublime works for me. 
Thanks.
